// Generated by CoffeeScript 1.9.3
(function() {
  var config, gameContainer, render, renderer, stage;

  config = require('./config');

  stage = new PIXI.Container();

  gameContainer = new PIXI.Graphics();

  gameContainer.interactive = true;

  gameContainer.hitArea = new PIXI.Rectangle(0, 0, config.WIDTH, config.HEIGHT);

  stage.addChild(gameContainer);

  renderer = PIXI.autoDetectRenderer(config.WIDTH, config.HEIGHT);

  renderer.autoResize = true;

  'document.getElementById(\'nav\').style.margin = \'0\'\ndocument.getElementById(\'nav\').style.border = \'0\'\ndocument.getElementById(\'nav\').style[\'border-radius\'] = \'0\'\ndocument.getElementById(\'nav\').style[\'background-color\'] = \'#AAA\'\n\nfor a in document.getElementById(\'nav\').getElementsByTagName \'a\'\n  a.style.color = \'#FFF\'\n  a.style[\'margin-right\'] = \'10px\'';

  document.body.appendChild(renderer.view);

  render = (function(_this) {
    return function(particleTree) {
      var drawParticles;
      gameContainer.clear();
      drawParticles = function(index) {
        var childIndices, i, id, j, len, particle, ref, results, results1;
        childIndices = particleTree.getValidChildIndicesByIndex(index);
        if (childIndices.length === 0) {
          ref = particleTree.nodes[index][particleTree._PARTICLES];
          results = [];
          for (id in ref) {
            particle = ref[id];
            gameContainer.beginFill(0x111111 * particle[2]);
            results.push(gameContainer.drawCircle(particle[0], particle[1], 5));
          }
          return results;
        } else {
          results1 = [];
          for (j = 0, len = childIndices.length; j < len; j++) {
            i = childIndices[j];
            results1.push(drawParticles(i));
          }
          return results1;
        }
      };
      drawParticles(0);
      return renderer.render(stage);
    };
  })(this);

  module.exports.render = render;

  module.exports.renderer = renderer;

  module.exports.gameContainer = gameContainer;

  module.exports.stage = stage;

}).call(this);
