// Generated by CoffeeScript 1.9.3
(function() {
  var a, config, gameContainer, j, len, ref, render, renderer, stage;

  config = require('./config');

  stage = new PIXI.Container();

  gameContainer = new PIXI.Graphics();

  gameContainer.interactive = true;

  gameContainer.hitArea = new PIXI.Rectangle(0, 0, config.WIDTH, config.HEIGHT);

  stage.addChild(gameContainer);

  renderer = PIXI.autoDetectRenderer(config.WIDTH, config.HEIGHT);

  renderer.autoResize = true;

  document.getElementById('nav').style.margin = '0';

  document.getElementById('nav').style.border = '0';

  document.getElementById('nav').style['border-radius'] = '0';

  document.getElementById('nav').style['background-color'] = '#AAA';

  ref = document.getElementById('nav').getElementsByTagName('a');
  for (j = 0, len = ref.length; j < len; j++) {
    a = ref[j];
    a.style.color = '#FFF';
    a.style['margin-right'] = '10px';
  }

  document.body.appendChild(renderer.view);

  render = (function(_this) {
    return function(particleTree) {
      var drawParticles;
      gameContainer.clear();
      drawParticles = function(index) {
        var childIndices, i, id, k, len1, particle, ref1, results, results1;
        childIndices = particleTree.getValidChildIndicesByIndex(index);
        if (childIndices.length === 0) {
          ref1 = particleTree.nodes[index][particleTree._PARTICLES];
          results = [];
          for (id in ref1) {
            particle = ref1[id];
            gameContainer.beginFill(0x111111 * particle[2]);
            results.push(gameContainer.drawCircle(particle[0], particle[1], 5));
          }
          return results;
        } else {
          results1 = [];
          for (k = 0, len1 = childIndices.length; k < len1; k++) {
            i = childIndices[k];
            results1.push(drawParticles(i));
          }
          return results1;
        }
      };
      drawParticles(0);
      return renderer.render(stage);
    };
  })(this);

  module.exports.render = render;

  module.exports.renderer = renderer;

  module.exports.gameContainer = gameContainer;

  module.exports.stage = stage;

}).call(this);
