// Generated by CoffeeScript 1.9.3
(function() {
  var Graphics, ParticleTree, config, mainLoop, particleTree, socket;

  Graphics = require('./graphics');

  config = require('./config');

  ParticleTree = require('./quadtree').ParticleTree;

  socket = io();

  particleTree = new ParticleTree(config.WIDTH, {
    x: 0,
    y: 0,
    width: config.WIDTH,
    height: config.WIDTH
  });

  Graphics.gameContainer.mouseup = Graphics.gameContainer.touchend = function(args) {
    var localPt;
    localPt = Graphics.gameContainer.toLocal(args.data.global);
    particleTree.addParticle(localPt.x, localPt.y);
  };

  require('./mouse-location-watch')(Graphics.gameContainer);

  document.takeSnapshot = require('./take-snapshot')(particleTree);

  (mainLoop = function() {
    particleTree.update(1);
    Graphics.render(particleTree);
    requestAnimationFrame(mainLoop);
  })();

}).call(this);
