// Generated by CoffeeScript 1.9.3
(function() {
  var Graphics, ParticleTree, config, mainLoop, particleQueue, particleTree;

  Graphics = require('./graphics');

  config = require('./config');

  ParticleTree = require('./quadtree').ParticleTree;

  particleTree = new ParticleTree(config.WIDTH);

  particleQueue = require('./queue')();

  mainLoop = function() {
    var mouse, mouseLoc, ref;
    mouse = Graphics.renderer.plugins.interaction.mouse;
    mouseLoc = mouse.getLocalPosition(Graphics.gameContainer);
    if (((ref = mouse.originalEvent) != null ? ref.type : void 0) === "mousedown") {
      particleTree.addParticle(mouseLoc.x, mouseLoc.y);
    }
    particleTree.update(1);
    Graphics.render(particleTree);
    return requestAnimationFrame(mainLoop);
  };

  mainLoop();

}).call(this);
