// Generated by CoffeeScript 1.9.3
(function() {
  var Account, LocalStrategy, app, bodyParser, cookieParser, dburl, express, expressSession, favicon, io, logger, mongoose, passport, path, ref, routes;

  path = require('path');

  logger = require('morgan');

  express = require('express');

  mongoose = require('mongoose');

  passport = require('passport');

  favicon = require('serve-favicon');

  bodyParser = require('body-parser');

  cookieParser = require('cookie-parser');

  expressSession = require('express-session');

  LocalStrategy = require('passport-local').Strategy;

  Account = require('./models/account');

  routes = require('./routes/index');

  app = express();

  io = require('socket.io')();

  app.io = io;

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json({
    limit: '50mb'
  }));

  app.use(bodyParser.raw({
    limit: '50mb'
  }));

  app.use(bodyParser.text({
    limit: '50mb'
  }));

  app.use(bodyParser.urlencoded({
    extended: false,
    limit: '50mb'
  }));

  app.use(cookieParser());

  app.use(expressSession({
    secret: 'mysecretthingy',
    resave: false,
    saveUninitialized: false
  }));

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use(passport.initialize());

  app.use(passport.session());

  passport.use(new LocalStrategy(Account.authenticate()));

  passport.serializeUser(Account.serializeUser());

  passport.deserializeUser(Account.deserializeUser());

  dburl = (ref = process.env.dburl) != null ? ref : require('./dburl');

  mongoose.connect(dburl);

  app.use('/', routes);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
