// Generated by CoffeeScript 1.9.3
(function() {
  var Queue, config, connectedSockets, numConnectedSockets, spectatingSockets;

  config = require('./config');

  Queue = require('./queue');

  connectedSockets = {};

  numConnectedSockets = 0;

  spectatingSockets = Queue();

  module.exports = function(http, particleTree) {
    var io;
    io = require("socket.io")(http);
    io.on('connection', function(socket) {
      if (numConnectedSockets >= config.MAX_CONNECTIONS) {
        socket.emit('Server full');
        return spectatingSockets.push(socket);
      } else {
        numConnectedSockets += 1;
        connectedSockets[socket.id] = socket;
        return socket.on('New Particle', function(particleData) {
          var id, mass, vx, vy, x, y;
          x = particleData.x;
          y = particleData.y;
          mass = particleData.mass;
          vx = particleData.vx;
          vy = particleData.vy;
          id = particleData.id;
          return particleTree.addParticle(x, y, mass, vx, vy, socket.id + id);
        });
      }
    });
    return io;
  };

}).call(this);
