// Generated by CoffeeScript 1.9.3
(function() {
  var Node, Queue;

  Node = (function() {
    function Node(value1, next, prev) {
      this.value = value1;
      this.next = next != null ? next : null;
      this.prev = prev != null ? prev : null;
    }

    return Node;

  })();

  Queue = (function() {
    function Queue() {}

    Queue.prototype.head = null;

    Queue.prototype.tail = null;

    Queue.prototype.push = function(value) {
      if (this.head === null) {
        this.head = this.tail = Node(value);
      } else {
        this.tail.next = Node(value, null, this.tail);
        this.tail = this.tail.next;
      }
      return value;
    };

    Queue.prototype.pop = function() {
      var toPop;
      toPop = this.head.value;
      this.head = this.head.next;
      return toPop;
    };

    return Queue;

  })();

  module.exports = Queue;

}).call(this);
