// Generated by CoffeeScript 1.9.3
(function() {
  var arr, i, j, ref, x;

  arr = (function() {
    var j, results;
    results = [];
    for (i = j = 0; j <= 100; i = ++j) {
      results.push(i);
    }
    return results;
  })();

  x = 0;

  for (i = j = ref = arr.length - 1; ref <= 0 ? j <= 0 : j >= 0; i = ref <= 0 ? ++j : --j) {
    x += 1;
  }

}).call(this);
