// Generated by CoffeeScript 1.9.3
(function() {
  var Account, express, passport, router;

  express = require('express');

  passport = require('passport');

  Account = require('../models/account');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('index', {
      user: req.user,
      title: 'IAP Project'
    });
  });

  router.get('/register', function(req, res) {
    return res.render('register', {});
  });

  router.post('/register', function(req, res) {
    return Account.register(new Account({
      username: req.body.username
    }), req.body.password, function(err, account) {
      if (err) {
        return res.render('register', {
          account: account
        });
      } else {
        passport.authenticate('local')(req, res, function() {
          return res.redirect('/');
        });
        return null;
      }
    });
  });

  router.get('/login', function(req, res) {
    return res.render('login', {
      user: req.user
    });
  });

  router.post('/login', passport.authenticate('local'), function(req, res) {
    return res.redirect('/');
  });

  router.get('/logout', function(req, res) {
    req.logout();
    return res.redirect('/');
  });

  router.get('/ping', function(req, res) {
    return res.status(200).send('pong!');
  });

  module.exports = router;

}).call(this);
