// Generated by CoffeeScript 1.9.3
(function() {
  var Account, Particle, Snapshot, convertToSnapshotModelInstance, express, passport, prettyDate, router;

  express = require('express');

  passport = require('passport');

  prettyDate = require('pretty-date');

  Account = require('../models/account');

  Snapshot = require('../models/snapshot');

  Particle = require('../models/particle');

  router = express.Router();

  router.get('/', function(req, res) {
    res.render('index', {
      user: req.user,
      title: 'IAP Project'
    });
  });

  router.get('/register', function(req, res) {
    res.render('register', {});
  });

  router.post('/register', function(req, res) {
    Account.register(new Account({
      username: req.body.username
    }), req.body.password, function(err, account) {
      if (err) {
        res.render('register', {
          account: account
        });
      } else {
        passport.authenticate('local')(req, res, function() {
          return res.redirect('/');
        });
      }
    });
  });

  router.get('/login', function(req, res) {
    res.render('login', {
      user: req.user
    });
  });

  router.post('/login', function(req, res, next) {
    return passport.authenticate('local', function(err, user, info) {
      if (err) {
        return next(err);
      } else if (!user) {
        return res.render('login', {
          attemptFail: true
        });
      } else {
        return req.login(user, function(err) {
          if (err) {
            return next(err);
          } else {
            return res.redirect('/');
          }
        });
      }
    })(req, res, next);
  });

  router.get('/logout', function(req, res) {
    req.logout();
    res.redirect('/');
  });

  router.get('/snapshots', function(req, res) {
    var user;
    user = req.user;
    if (user) {
      res.render('snapshots', {
        user: user,
        prettifyDate: prettyDate.format
      });
    } else {
      res.redirect('/');
    }
  });

  router.get('/snapshot', function(req, res) {
    var snapshot;
    if (!req.user) {
      res.redirect('/');
    }
    snapshot = ((function() {
      var j, len, ref, results;
      ref = req.user.snapshots;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        snapshot = ref[j];
        if (snapshot._id + "" === req.query.snapshotid + "") {
          results.push(snapshot);
        }
      }
      return results;
    })())[0];
    if (snapshot) {
      return res.render('snapshot', {
        user: req.user,
        snapshotparticles: snapshot.particles
      });
    } else {
      return res.redirect('/');
    }
  });

  convertToSnapshotModelInstance = function(particles) {
    var i, j, particleModelInstances, ref;
    particleModelInstances = new Array(particles.xs.length);
    for (i = j = 0, ref = particles.xs.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      particleModelInstances[i] = new Particle({
        x: particles.xs[i],
        y: particles.ys[i],
        mass: particles.masses[i],
        vx: particles.vxs[i],
        vy: particles.vys[i]
      });
    }
    return new Snapshot({
      particles: particleModelInstances
    });
  };

  router.post('/takesnapshot', function(req, res) {
    var snapshot;
    if (req.user) {
      snapshot = convertToSnapshotModelInstance(req.body);
      Account.findByIdAndUpdate(req.user._id, {
        $push: {
          snapshots: snapshot
        }
      }, {
        safe: true,
        upsert: true
      }, function(err, model) {
        if (err) {
          console.log(err);
          res.send({
            message: 'Snapshot Failed. Please try again'
          });
        } else {
          res.send({
            message: 'Snapshot Successful!'
          });
        }
      });
    } else {
      res.send({
        message: 'Snapshot Failed. Log in and try again'
      });
    }
  });

  module.exports = router;

}).call(this);
